# Generated by Django 6.0.3 on 2026-03-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bookingrequest_requester_alter_item_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
