# Generated by Django 6.0.3 on 2026-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_category_item_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='pickup_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/'),
        ),
        migrations.AddField(
            model_name='item',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rented', 'Rented'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
