# Generated by Django 6.0.3 on 2026-03-08 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookingrequest_pickup_qr_bookingrequest_return_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='item',
            name='deposit',
        ),
        migrations.AddField(
            model_name='item',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
