# Generated by Django 6.0.3 on 2026-04-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_item_deposit_amount_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True),
        ),
    ]
